server:
  port: 53002
#################################
## SECURITY
#################################
security:
  basic:
    enabled:  false
management:
  security:
    enabled:  false
    ignored:  /css/**

#################################
## DATASOURCE
#################################

spring:
  datasource:
    url: jdbc:mysql://120.55.42.29:3306/ak_blog?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: noneone168
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 1
    maxActive: 30
    minIdle: 5
    maxWaite: 600000
    testOnBorrow: true
    test-while-idle: true



  messages:
    basename: messages/message,messages/message-fw
    cache-seconds: -1
    encoding: UTF-8


#################################
## Redis
#################################
#  redis:
#    database: 8
#    host: 192.168.91.129
#    port: 6379
#    timeout: 50000
#    password: admin
#    pool:
#      maxActive: 300
#      maxIdle: 100
#      maxWait: 10000
#      minIdle: 0

  #设置上传文件大小
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  #设置LocalDateTime、LocalDate等日期类型支持序列化
  jackson:
    serialization:
      write-dates-as-timestamps: false

  #禁用自启动
#  devtools:
#    restart:
#      enabled: false
      
# LOGGING
logging:
  level:
    root: info
    com:
      iyb:
        ak: debug

#################################
## session
#################################

session:
  timeout: 3600000



eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka/
    register-with-eureka: true
  instance:
    prefer-ip-address: true


# Hystrix
#hystrix:
#  command:
#    default:
#      execution:
#        timeout.enabled: true
#        isolation:
#          strategy: THREAD
#          thread:
#            timeoutInMilliseconds: 3000


#spring.cloud.loadbalancer.retry.enabled: false


ribbon:
  ReadTimeout: 0
  ConnectTimeout: 10
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  OkToRetryOnAllOperations: false
  eager-load:
    enabled: true
    clients: ak
  eureka:
    enabled: true



feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        timeout.enabled: true
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 2000
#    强制打开熔断状态
#    getContents:
#      circuitBreaker:
#        forceOpen: false
